### ISSUE TITLE
Request: Downgrade node requirement unless you really need it

### ISSUE THREAD

**Issue by leandrooriente** [ikrishg/reseter.css#13]
**Is your feature request related to a problem? Please describe.**
We are using the LTS version of Node which is not supported by this package.

**Describe the solution you'd like**
Downgrade the required Node version to the latest LTS.

**Describe alternatives you've considered**
Upgrading to a non-LTS version is not possible on the project I'm currently working, so not much that can be done here.

**Additional context**
<img width="646" alt="Screenshot 2021-04-08 at 20 31 59" src="https://user-images.githubusercontent.com/1781007/114078617-797c0d00-98a9-11eb-82c4-1aec3c199aa9.png">

**Comment by ghost** [comment]
Sorry, For The Inconvenience. I used a template for the `package.json` and didn't change that. `Reseter.css`  as told is a 0 dependency project. It only requires dependencies for development. From Version `1.1.0` it is fixed! Thanks!

Try Running This Again
```bash
yarn add reseter.css@latest
```

**Comment by ghost** [comment]
@all-contributors add @leandrooriente for bugs

**Comment by ghost** [comment]
Thanks For Contributing @leandrooriente

We are planning to create a showcase of projects in our readme. So We'll Love If You would like to share the URL and screenshot when done!
