### ISSUE TITLE
Bug: incorrect selector for disabled buttons

### ISSUE THREAD

**Issue by rmatsuda21** [ikrishg/reseter.css#139]
Noticed an issue where the pointer style is being applied to buttons even though they are disabled. 
Here is the current code that provides this styling.
```
[type='button']:not(disabled),
[type='reset']:not(disabled),
[type='submit']:not(disabled),
button:not(disabled) {
  cursor: pointer;
}
```

I believe that to proper select disabled buttons we have to do it this way:
```
[type='button']:not([disabled]),
[type='reset']:not([disabled]),
[type='submit']:not([disabled]),
button:not([disabled]) {
  cursor: pointer;
}
```

However, can we not just utilize the [`:enabled`](https://developer.mozilla.org/en-US/docs/Web/CSS/:enabled) selector?

**Comment by thepushp** [comment]
Hi can you assign this issue to me

**Comment by GaryHilares** [comment]
Hi @thepushp! Are you still interested in working on this issue?

**Comment by fayazpn** [comment]
Hello, Interested in solving this issue.

**Comment by GaryHilares** [comment]
Hey @Fayaz-B! You can work on it if you want.
