### ISSUE TITLE
Adding colours to the documentation website for better experience.

### ISSUE THREAD

**Issue by bhavyasingh75** [ikrishg/reseter.css#146]
![Screenshot (66)](https://user-images.githubusercontent.com/102183018/197841503-fb1dcf61-40e5-466a-8f57-12fda9a4618d.png)

I liked the documentation a lot. Could you add some colourful shades so that the docs become a bit easy to read? I tried changing the color temporarily, which looked better.

**Comment by Abhishek2nayak** [comment]
I want to work on his issue. may i work on it ?

**Comment by bhavyasingh75** [comment]
Go ahead.

**Comment by GaryHilares** [comment]
I think this issue is outdated (the website does not longer exist). It probably should be closed.

**Comment by gptkrsh** [comment]
The website is the markdown file 'README.md', it still exists but we no-longer promote it, since reading the readme file is better. And we cannot have colours for the same reason. Thanks for the suggestion though
