### ISSUE TITLE
Placeholder opacity in FireFox

### ISSUE THREAD

**Issue by ghost** [ikrishg/reseter.css#16]
**Is your feature request related to a problem? Please describe.**
FireFox (latest version as of posting) has a slightly lower opacity for input placeholders. See my screenshot below. You fix this with:

I suggest adding it to reseter.css.

**Describe the solution you'd like**
Fix The Issue By Adding `input::placeholder { opacity: 1; }` to reseter.css

**Additional context**
![screeshot](https://user-images.githubusercontent.com/7329623/105620692-283da080-5dc5-11eb-8586-2fc459f8bb15.PNG)

Originally Publish By @starkana in sindresorhus/modern-normalize#46

**Comment by krishdevdb** [comment]
Thanks For Contributing To Reseter.css. Make sure you follow our contributing guidelines. Our Maintainers Will Review Your Issue Soon! Happy Hacking!

**Comment by ghost** [comment]
Waiting For Some One To Grab This Good First Issue! Well if anyone is interested kindly comment here (I'll Assign It You And Only You)

**Comment by himanshu007-creator** [comment]
I would like to work on this issue!!

**Comment by ghost** [comment]
Wonderful I have assigned it to you!

**Comment by ghost** [comment]
@all-contributors please add @starkana for bug, code
