### ISSUE TITLE
[Docs]: Table markup is not displaying correctly

### ISSUE THREAD

**Issue by GaryHilares** [ikrishg/reseter.css#168]
### Description

The table markup in the README.md is displaying the markup as text instead of the actual table

### Anything else?

![README.md table screenshot](https://user-images.githubusercontent.com/46727048/210280213-5c75f57c-8e2a-4128-b85a-fec606763ffd.png)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/krshkun/gardevoir/blob/main/CODE_OF_CONDUCT.md)

**Comment by gptkrsh** [comment]
Thanks for reporting 👍 Assigning you since you made a PR
