### ISSUE TITLE
Docs:  Reseter.css Web Site Display Bug 

### ISSUE THREAD

**Issue by yamanoku** [ikrishg/reseter.css#25]
**Describe the bug**
Under the Tweet and GitHub star buttons display bug

**To Reproduce**

1. Go to https://krishdevdb.github.io/reseter.css/
2. See bug

**Expected behavior**
Not display bug

**Screenshots**
<img width="1128" alt="Screen Shot 2021-04-13 at 12 16 24" src="https://user-images.githubusercontent.com/1996642/114492657-f285b680-9c53-11eb-828d-c7fada0cf824.png">
<img width="1203" alt="Screen Shot 2021-04-13 at 12 16 32" src="https://user-images.githubusercontent.com/1996642/114492665-f580a700-9c53-11eb-9139-c8ccd572a031.png">

**Desktop (please complete the following information):**

- OS: macOS Catalina ver 10.15.7
- Browser: Chrome
- Version: Version 89.0.4389.114 (Official Build) (x86_64)

**Additional context**
Is it a bug specific to GitHub Pages?

**Comment by ghost** [comment]
I think there's some issue in jekyll's md parser that github uses. cause the readme is same as this projects readme. Let me re-create the page

**Comment by ghost** [comment]
I will ask github support about it

**Comment by ghost** [comment]
@yamanoku I added the query to github support community:

https://github.community/t/tables-not-rendering-in-github-pages/174235

**Comment by ghost** [comment]
Well thanks for being interested in reseter.css.

**Comment by ghost** [comment]
@all-contributors please add @yamanoku for doc

**Comment by ghost** [comment]
I didn't got reply yet from the community support so instead of waiting. I'll change the page source to html for now

**Comment by ghost** [comment]
> I didn't got reply yet from the community support so instead of waiting. I'll change the page source to html for now

@yamanoku I've fixed It now. I've added a html page for display. Know it works fine. Thanks for reporting the issue.
