### ISSUE TITLE
Bug: Several separate words we combines into one — but shouldn’t

### ISSUE THREAD

**Issue by lsprr** [ikrishg/reseter.css#32]
**Describe the bug**
Please see screenshots

**To Reproduce**

1. Go to https://krishdevdb.github.io/reseter.css/
2. Read the entire page, and you will see several separate words we combine into one — but shouldn’t. 

**Screenshots**
![image](https://user-images.githubusercontent.com/16653744/115947858-89464480-a498-11eb-9573-2fe1cc4d0381.png)
![image](https://user-images.githubusercontent.com/16653744/115947876-a11dc880-a498-11eb-9372-ecbd3b630b3a.png)
![image](https://user-images.githubusercontent.com/16653744/115947886-ada22100-a498-11eb-95e7-0d56825f701b.png)
![image](https://user-images.githubusercontent.com/16653744/115947900-c01c5a80-a498-11eb-8c43-50adcf7d6cf0.png)
![image](https://user-images.githubusercontent.com/16653744/115947916-d32f2a80-a498-11eb-84b8-2d81002fadac.png)
![image](https://user-images.githubusercontent.com/16653744/115947922-db876580-a498-11eb-99a4-a428656fc2c4.png)

**Desktop (please complete the following information):**

- OS: [Windows 10 Pro build 19042.928]
- Browser [Firefox Developer Edition]
- Version [89.0b3]

**Additional context**
Is it a bug specific to GitHub Pages?

**Comment by ghost** [comment]
Thanks @lsprr
