### ISSUE TITLE
Gather Issues!

### ISSUE THREAD

**Issue by ghost** [ikrishg/reseter.css#37]
A humble request to everyone reading this. I request you to kindly, check out other CSS resets and normalizers. Find some issues or bugs in them using the bug tracker. Then repost it to this repository. Make sure to link to the actual issue, of the repo where you found it.

For example, #19 and #16 are taken from `@starkana in sindresorhus/modern-normalize#46` and `@Gaboris at necolas/normalize.css#851` respectively.

Thanks! Please Mention This Issue In Your Issue So That Everyone Reading This Page Will Get To Know What All Issues Have Been Made!

**Comment by Blazing-Mike** [comment]
How would I repost other bugs I find in other repo here? I should post it here on the comment or open a new issue?

**Comment by ghost** [comment]
> How would I repost other bugs I find in other repo here? I should post it here on the comment or open a new issue?

You can create a new issue 🙂 It will also earn you a contribution point
