### ISSUE TITLE
h1, ..., h6 rules (margin and font) : "Invalid property value"

### ISSUE THREAD

**Issue by dajoha** [ikrishg/reseter.css#42]
https://github.com/krishdevdb/reseter.css/blob/fe8d92687a8cc34207cddc27c924dd4d6f6c7919/css/reseter.css#L70-L78

These rules seem to be not understood by at least two major browsers (Firefox 88 and Vivaldi 3.7).

For the margin, replacing `initial` by another value like `auto` or `0` removes the error.

**Comment by ghost** [comment]
@yolenoyer Thanks For Contributing To This Project

@all-contributors please add @yolenoyer for bug
