### ISSUE TITLE
Bug: Linguistic Issue and referential issue in the readme.md

### ISSUE THREAD

**Issue by meenal21** [ikrishg/reseter.css#46]
**Describe the bug**
Going through the 'Why do I use a CSS Reset' part, I noticed that there is a Firefox browser referenced in the table, but instead of the firefox heading, the heading says 'with Resetter.css'.

Also, on the first line of this section, instead of using 'Down is the result', which could be misleading as the status of the website, 'Below is the result' can be used.  

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to the ReadMe.md page.
2. Go to section 'Why do I use a CSS Reset'
3. See the error

**Expected behaviour**
The table heading should say Firefox, instead of 'with Resetter.css'

**Screenshots**
![image](https://user-images.githubusercontent.com/13515337/119439842-cffdb780-bd40-11eb-93f6-ff6e4e48cd14.png)

**Desktop (please complete the following information):**
- NA

**Smartphone (please complete the following information):**
- NA

**Additional context**

**Comment by ghost** [comment]
Thanks for opening this issue @meenal21 a fix will be made soon

@all-contributors please add @meenal21 for bug and doc

**Comment by ghost** [comment]
@meenal21 You are a new a contributor to github 🎉 We encourage new contributors and people into the community. Here are a few resources for you:

- [Eddie Jaoude Youtube Channel](https://www.youtube.com/eddiejaoude)
- [EddieHubCommunity](https://github.com/EddieHubCommunity)

**Comment by meenal21** [comment]
Hey @krishdevdb, I see that after changes there is a link added, but when I click the link, it seems to be broken. Can you have a look at it.

![image](https://user-images.githubusercontent.com/13515337/119458214-20cdda00-bd5a-11eb-8d38-3e0dd79678b5.png)

![image](https://user-images.githubusercontent.com/13515337/119458250-2aefd880-bd5a-11eb-9c50-bbf32bfee4a9.png)

**Comment by ghost** [comment]
@meenal21 I have fixed it now. It was a branch issue 😅
