### ISSUE TITLE
Bug: Broken Image In README

### ISSUE THREAD

**Issue by verma-kunal** [ikrishg/reseter.css#49]
**Describe the bug**
There is an image in the Readme file, that has broken due to some reason.

**Screenshots**

![Screenshot 2021-05-25 at 2 43 26 PM](https://user-images.githubusercontent.com/72245772/119472120-91c7be80-bd67-11eb-91c3-06e5daa36525.png)

**Comment by ghost** [comment]
Thanks for opening this issue. We highly appreciate your contribution 🎉 

@all-contributors please add @verma-kunal for docs and bug
