### ISSUE TITLE
font-family for pre/code

### ISSUE THREAD

**Issue by tracker1** [ikrishg/reseter.css#5]
FYI, using the following, from my own list, and integrated the one in the repository.

```
pre,
code,
kbd,
samp {
  font-family: "Fira Code", 
    "Cascadia Code", 
    Consolas, 
    "Inconsolata",
    Monaco,
    Menlo,
    "Noto Mono",
    "Roboto Mono",
    "Droid Sans Mono", 
    "Ubuntu Mono",
    "Ubuntu Monospace",
    "Source Code Pro", 
    "Oxygen Mono",
    "Liberation Mono", 
    "DejaVu Sans Mono", 
    "Bitstream Vera Sans Mono", 
    monospace,
    "Apple Color Emoji",
    "Segoe UI Emoji",
    "Segoe UI Symbol",
    "Noto Color Emoji";
  font-size: 1.04rem;
}
```

The developer fonts above represent some of the more common fonts, all of which will render/display better than the default which is often a Courier derivative.  The above fonts list are all sans-serif developer fonts with an aesthetic which will at least be closer to the default font family.

Reason on the ordering...

- `Fira Code` - the most complete font in terms of fixed width with width-proper emojii support.
- `Cascadia Code` - Windows (newer)
- `Consolas` - Windows (common)
- `Inconsolata` - Consolas look-alike, open-source.
- `Droid Sans Mono` - Android
- `Monaco` - MacOS
- `Menlo` - iOS
- others - more common alternative fonts installed on different platforms
- monospace - Default fallback
- *Emoji - emoji character supprt as fallback

**Comment by ghost** [comment]
So You Want These Font To Be Added @tracker1 .

**Comment by ghost** [comment]
But why have you changed the font by adding 0.4rem

**Comment by tracker1** [comment]
@krishdevdb adding them would be cool.. order might be better, as the order above is more likely in popularity, though giving Fira Code preference only because of its' completeness.

As to the 1,04rem on the font-size,  for the handful of fonts I tested, the fixed-width fonts look a hair smaller than the sans fonts.

**Comment by ghost** [comment]
I have added the fonts and I will change the font sizing as well in the next committ

**Comment by ghost** [comment]
I have changed everything you have mentioned. Thanks for contributing @tracker1

**Comment by krishdevdb** [comment]
@all-contributors add @tracker1 Code

**Comment by krishdevdb** [comment]
@all-contributors add @tracker1 for Code

**Comment by krishdevdb** [comment]
@all-contributors add @tracker1 for Code

**Comment by krishdevdb** [comment]
@all-contributors add @tracker1 for code

**Comment by krishdevdb** [comment]
@all-contributors add @tracker1 for code

**Comment by ghost** [comment]
@all-contributors add @tracker1 for code

**Comment by ghost** [comment]
Hey @tracker1  We are planning to create a showcase for projects using reseter.css. If you would like to please share the url and screenshot of the project in which you use reseter.css

**Comment by tracker1** [comment]
@krishdevdb I really can't since nothing I've used it with is really public facing as of yet.

**Comment by ghost** [comment]
> @krishdevdb I really can't since nothing I've used it with is really public facing as of yet.

Thanks for the update! Make sure to tell us when you publish a website that uses reseter.css
