### ISSUE TITLE
[Feat]: paragraph spacing

### ISSUE THREAD

**Issue by tracker1** [ikrishg/reseter.css#53]
### Detailed Description

Don't have time for a PR at the moment, appended to my local copy, but probably a good idea to add..

```
p + p {
  margin-top: 1rem;
}
```

### Contributing

- [X] I have read the project's contribution guidelines.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gouravmohanty7070** [comment]
I would love to solve the issue if anyone isn't working on it currently!

**Comment by ghost** [comment]
Ya sure @gouravmohanty7070!

**Comment by ghost** [comment]
Here is a step by step guide

- Add the code mentioned in the issue to src/scss/global.scss
- Copy the content of src/scss/global.scss to src/less/global.less
- Add this code to src/sass/global.sass
  
  ```sass
  p + p
    margin-top: 1rem
  ```
- Copy the contents of src/sass/global.sass to src/styl/global.styl
- Build the code, you are done 🎉

**Comment by Narcos101** [comment]
is @gouravmohanty7070 still on it? And can I work on it?

**Comment by gouravmohanty7070** [comment]
@Narcos101 Yes bro! I got this issue today itself. I am working on it

**Comment by gouravmohanty7070** [comment]
@krishdevdb aren't the code mentioned in the issue and the code to be copied in sis/sass/global.css same?
So, it means the same line of code is to be added in both global.sass and global.scss?

**Comment by ghost** [comment]
Thanks for the contributions @tracker1 and @gouravmohanty7070! Don't worry @Narcos101 we have another issue for ya #37
