### ISSUE TITLE
Request: 

### ISSUE THREAD

**Issue by Dipen-Dedania** [ikrishg/reseter.css#6]
**Is your feature request related to a problem? Please describe.**
I like the idea to reseter to have a consistent UI throughout all the browsers. I tried the mentioned demo in the readme.md and it loads the UI better but still it varies in the different browsers. I have tried with

1. Chrome
2. Microsoft edge
3. Firefox

You can refer the attached screenshot for details.
![image](https://user-images.githubusercontent.com/5135662/109789400-4d2ff980-7c36-11eb-8785-0cd92535fbe6.png)

**Comment by krishdevdb** [comment]
Hi @Dipen-Dedania. Thanks For Contributing. But It Might Be A Little Helpful If You Tell Us Some More Details.

**Comment by krishdevdb** [comment]
This Seems To Be A Bug. Kindly Provide The Details Related To It Using The Bug Template: [Click This](https://github.com/krishdevdb/reseter.css/issues/new?assignees=krishdevdb&labels=bug&template=bug-report.md&title=Bug%3A+)

> Kindly Close This Issue When Open The Issue With The Bug Template

**Comment by krishdevdb** [comment]
If you don't reply anything I am closing this issue. But As Per Your Screen Shot Everything Looks Same.

**Comment by ghost** [comment]
@Dipen-Dedania The Browsers You Have Opened Are Of Different Sizes. Try Maximizing all of them to get the same result. As, Reseter.css supports Responsive Font Sizing
