### ISSUE TITLE
Documentation link broken in the About section

### ISSUE THREAD

**Issue by yashsehgal** [ikrishg/reseter.css#68]
Hey @krishdevdb 👋🏽 This docs link is broken in the about section of this repository, please do fix it.

Also, I was looking at this project and you all have maintained it well. Pretty good!! Keep it up folks 🔥

**Comment by deepmalamittal** [comment]
I can work on this issue. What should be the correct link?
https://github.com/resetercss/reseter.css?

**Comment by yashsehgal** [comment]
Hey @deepmalamittal 👋🏽 Thanks for showing interest 🔥 

@krishdevdb Can you look into this issue and assign it to @deepmalamittal if possible?

**Comment by deepmalamittal** [comment]
Here is the pull request for the same: https://github.com/resetercss/reseter.css/pull/84

**Comment by virajrg108** [comment]
Is this issue fixed? If not then I would like to work on this

**Comment by MeetaHaldar** [comment]
can i help some??

**Comment by YasarArafathAli** [comment]
Can you assign this issue to me, I would Like to help. Thanks

**Comment by code-rohitr** [comment]
Please provide the correct link to the documentation.

**Comment by curtisbarnard** [comment]
The correct link is https://resetercss.github.io/reseter.css/ I believe. I think the owner of the repo has to update it though?

![image](https://user-images.githubusercontent.com/100104319/168930343-52815678-0858-45d4-b337-2a3f1c8cd805.png)

**Comment by paryswest** [comment]
Is this issue still good to work on? As someone stated above, the link seems good, the owner has to add it, however.

**Comment by MilderBronze** [comment]
Is this project being worked on by anyone? Please let me know if there are any issues that I can work on.

**Comment by joannasjohnraj** [comment]
@krishdevdb Is this issue still open? If it is can you assign it to me, I would like to work on it.

**Comment by aniketghosh01** [comment]
@krishdevdb If this issue is still unsolved, I would like to contribute. Please assign me to it. Thank You.

**Comment by prinshukumar22** [comment]
@krishdevdb I would like to solve this issue give it to me

**Comment by gptkrsh** [comment]
Thanks for the involvement, everyone, but I don't know how, y'all except Yash, tagged my previous account, which led to me not getting the notification. The link in the sidebar can only be updated by staff 👍 I am doing it now
