### ISSUE TITLE
Bug: Missing Images at https://krishdevdb.github.io/

### ISSUE THREAD

**Issue by joejenett** [ikrishg/reseter.css#7]
Just to be helpful - in the "Why use...(must read)" section of the page at https://krishdevdb.github.io/, the 3 images are missing.

**Comment by ghost** [comment]
Thanks for showing interest in **reseter.css**. I got to know the error. I have fixed It Now You Can View The [Website](https://krishdevdb.github.io/).

**Comment by ghost** [comment]
@all-contributors add @joejenett for bug and doc

**Comment by ghost** [comment]
Hey @joejenett We are planning to create a showcase for projects using reseter.css. If you would like to please share the url and screenshot of the project in which you use reseter.css
