### ISSUE TITLE
Hide Packages

### ISSUE THREAD

**Issue by gptkrsh** [ikrishg/reseter.css#88]
![image](https://user-images.githubusercontent.com/91655303/145218710-84e18c81-9ab1-4280-99eb-da0ae76461f5.png)

**Comment by danishhansari** [comment]
Can u just elaborate what that issues is This is my first contribution

**Comment by gptkrsh** [comment]
Actually this can only be done by maintainers

**Comment by GaryHilares** [comment]
@krshkun. Probably you should solve this one (You're the one with permissions to do so).

**Comment by gptkrsh** [comment]
Thank you! Did it, it had gone out of my track unfortunately
