### ISSUE TITLE
showcase.png Image not showing 

### ISSUE THREAD

**Issue by AjRadwan** [ikrishg/reseter.css#96]
@krishdevdb 

```
showcase image needs to be fixed 
```
- There seems to be some issue with Image 
-  and there is no space after the mark sign I think It will look better if it's fixed 

![Screenshot_1](https://user-images.githubusercontent.com/43091820/148027162-bbc0daee-d7d4-4abc-aa43-e860b853f28b.png)

**Comment by EliavYair1** [comment]
can you assign this issue to me?

**Comment by shagungarg0** [comment]
can i work on this issue??

**Comment by AjRadwan** [comment]
@EliavYair1, @shagungarg0  the issue has been solved it just needs to marge together,  
thank you for your comment
